rules:
  react/jsx-filename-extension:
  - error
  - allow: as-needed
    extensions:
      - ".tsx"
  react/react-in-jsx-scope: off
  react/require-default-props: off
  react/function-component-definition:
  - error # recommended off
  - namedComponents: arrow-function
    unnamedComponents: arrow-function