extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
overrides:
  - files:
      - "**/*.ts?(x)"
    parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"